[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aveo_hook = "ExAoxPmugpGbYTVB31oDTqkkG12PM6neFq4vhM6LJd33"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'on-chain tests live in tests/onchain'"
